// Code generated by protoc-gen-go. DO NOT EDIT.
// source: conman.proto

package server

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CreateContainerRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Rootfs               string   `protobuf:"bytes,2,opt,name=rootfs" json:"rootfs,omitempty"`
	Command              []string `protobuf:"bytes,3,rep,name=command" json:"command,omitempty"`
	Args                 []string `protobuf:"bytes,4,rep,name=args" json:"args,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateContainerRequest) Reset()         { *m = CreateContainerRequest{} }
func (m *CreateContainerRequest) String() string { return proto.CompactTextString(m) }
func (*CreateContainerRequest) ProtoMessage()    {}
func (*CreateContainerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_conman_75f84094734f4100, []int{0}
}
func (m *CreateContainerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateContainerRequest.Unmarshal(m, b)
}
func (m *CreateContainerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateContainerRequest.Marshal(b, m, deterministic)
}
func (dst *CreateContainerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateContainerRequest.Merge(dst, src)
}
func (m *CreateContainerRequest) XXX_Size() int {
	return xxx_messageInfo_CreateContainerRequest.Size(m)
}
func (m *CreateContainerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateContainerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateContainerRequest proto.InternalMessageInfo

func (m *CreateContainerRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateContainerRequest) GetRootfs() string {
	if m != nil {
		return m.Rootfs
	}
	return ""
}

func (m *CreateContainerRequest) GetCommand() []string {
	if m != nil {
		return m.Command
	}
	return nil
}

func (m *CreateContainerRequest) GetArgs() []string {
	if m != nil {
		return m.Args
	}
	return nil
}

type CreateContainerResponse struct {
	ContainerId          string   `protobuf:"bytes,1,opt,name=container_id,json=containerId" json:"container_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateContainerResponse) Reset()         { *m = CreateContainerResponse{} }
func (m *CreateContainerResponse) String() string { return proto.CompactTextString(m) }
func (*CreateContainerResponse) ProtoMessage()    {}
func (*CreateContainerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_conman_75f84094734f4100, []int{1}
}
func (m *CreateContainerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateContainerResponse.Unmarshal(m, b)
}
func (m *CreateContainerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateContainerResponse.Marshal(b, m, deterministic)
}
func (dst *CreateContainerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateContainerResponse.Merge(dst, src)
}
func (m *CreateContainerResponse) XXX_Size() int {
	return xxx_messageInfo_CreateContainerResponse.Size(m)
}
func (m *CreateContainerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateContainerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateContainerResponse proto.InternalMessageInfo

func (m *CreateContainerResponse) GetContainerId() string {
	if m != nil {
		return m.ContainerId
	}
	return ""
}

type StartContainerRequest struct {
	ContainerId          string   `protobuf:"bytes,1,opt,name=container_id,json=containerId" json:"container_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartContainerRequest) Reset()         { *m = StartContainerRequest{} }
func (m *StartContainerRequest) String() string { return proto.CompactTextString(m) }
func (*StartContainerRequest) ProtoMessage()    {}
func (*StartContainerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_conman_75f84094734f4100, []int{2}
}
func (m *StartContainerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartContainerRequest.Unmarshal(m, b)
}
func (m *StartContainerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartContainerRequest.Marshal(b, m, deterministic)
}
func (dst *StartContainerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartContainerRequest.Merge(dst, src)
}
func (m *StartContainerRequest) XXX_Size() int {
	return xxx_messageInfo_StartContainerRequest.Size(m)
}
func (m *StartContainerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StartContainerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StartContainerRequest proto.InternalMessageInfo

func (m *StartContainerRequest) GetContainerId() string {
	if m != nil {
		return m.ContainerId
	}
	return ""
}

type StartContainerResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartContainerResponse) Reset()         { *m = StartContainerResponse{} }
func (m *StartContainerResponse) String() string { return proto.CompactTextString(m) }
func (*StartContainerResponse) ProtoMessage()    {}
func (*StartContainerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_conman_75f84094734f4100, []int{3}
}
func (m *StartContainerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartContainerResponse.Unmarshal(m, b)
}
func (m *StartContainerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartContainerResponse.Marshal(b, m, deterministic)
}
func (dst *StartContainerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartContainerResponse.Merge(dst, src)
}
func (m *StartContainerResponse) XXX_Size() int {
	return xxx_messageInfo_StartContainerResponse.Size(m)
}
func (m *StartContainerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StartContainerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StartContainerResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*CreateContainerRequest)(nil), "CreateContainerRequest")
	proto.RegisterType((*CreateContainerResponse)(nil), "CreateContainerResponse")
	proto.RegisterType((*StartContainerRequest)(nil), "StartContainerRequest")
	proto.RegisterType((*StartContainerResponse)(nil), "StartContainerResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Conman service

type ConmanClient interface {
	CreateContainer(ctx context.Context, in *CreateContainerRequest, opts ...grpc.CallOption) (*CreateContainerResponse, error)
	StartContainer(ctx context.Context, in *StartContainerRequest, opts ...grpc.CallOption) (*StartContainerResponse, error)
}

type conmanClient struct {
	cc *grpc.ClientConn
}

func NewConmanClient(cc *grpc.ClientConn) ConmanClient {
	return &conmanClient{cc}
}

func (c *conmanClient) CreateContainer(ctx context.Context, in *CreateContainerRequest, opts ...grpc.CallOption) (*CreateContainerResponse, error) {
	out := new(CreateContainerResponse)
	err := grpc.Invoke(ctx, "/Conman/CreateContainer", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *conmanClient) StartContainer(ctx context.Context, in *StartContainerRequest, opts ...grpc.CallOption) (*StartContainerResponse, error) {
	out := new(StartContainerResponse)
	err := grpc.Invoke(ctx, "/Conman/StartContainer", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Conman service

type ConmanServer interface {
	CreateContainer(context.Context, *CreateContainerRequest) (*CreateContainerResponse, error)
	StartContainer(context.Context, *StartContainerRequest) (*StartContainerResponse, error)
}

func RegisterConmanServer(s *grpc.Server, srv ConmanServer) {
	s.RegisterService(&_Conman_serviceDesc, srv)
}

func _Conman_CreateContainer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateContainerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConmanServer).CreateContainer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Conman/CreateContainer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConmanServer).CreateContainer(ctx, req.(*CreateContainerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Conman_StartContainer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartContainerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConmanServer).StartContainer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Conman/StartContainer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConmanServer).StartContainer(ctx, req.(*StartContainerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Conman_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Conman",
	HandlerType: (*ConmanServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateContainer",
			Handler:    _Conman_CreateContainer_Handler,
		},
		{
			MethodName: "StartContainer",
			Handler:    _Conman_StartContainer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "conman.proto",
}

func init() { proto.RegisterFile("conman.proto", fileDescriptor_conman_75f84094734f4100) }

var fileDescriptor_conman_75f84094734f4100 = []byte{
	// 237 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x91, 0xc1, 0x4a, 0x03, 0x31,
	0x10, 0x86, 0xbb, 0xb6, 0xac, 0x76, 0x14, 0x85, 0x01, 0xb3, 0xa1, 0xa7, 0x9a, 0x53, 0x4f, 0x39,
	0xe8, 0x4d, 0x3c, 0x19, 0x10, 0xbc, 0xae, 0x37, 0x2f, 0x12, 0xbb, 0xa3, 0xf4, 0x90, 0x4c, 0x9d,
	0x44, 0xdf, 0xc4, 0xf7, 0x15, 0xd3, 0x2a, 0xd8, 0x5d, 0xa1, 0xb7, 0x99, 0x1f, 0x26, 0xdf, 0x97,
	0x19, 0x38, 0x59, 0x72, 0x0c, 0x3e, 0xda, 0xb5, 0x70, 0x66, 0x23, 0xa0, 0x9c, 0x90, 0xcf, 0xe4,
	0x38, 0x66, 0xbf, 0x8a, 0x24, 0x2d, 0xbd, 0xbd, 0x53, 0xca, 0x88, 0x30, 0x89, 0x3e, 0x90, 0xae,
	0xe6, 0xd5, 0x62, 0xda, 0x96, 0x1a, 0x15, 0xd4, 0xc2, 0x9c, 0x5f, 0x92, 0x3e, 0x28, 0xe9, 0xb6,
	0x43, 0x0d, 0x87, 0x4b, 0x0e, 0xc1, 0xc7, 0x4e, 0x8f, 0xe7, 0xe3, 0xc5, 0xb4, 0xfd, 0x69, 0xbf,
	0x5f, 0xf1, 0xf2, 0x9a, 0xf4, 0xa4, 0xc4, 0xa5, 0x36, 0x37, 0xd0, 0xf4, 0x98, 0x69, 0xcd, 0x31,
	0x11, 0x5e, 0x14, 0xbd, 0x4d, 0xf8, 0xb4, 0xea, 0xb6, 0xf0, 0xe3, 0xdf, 0xec, 0xbe, 0x33, 0xd7,
	0x70, 0xfe, 0x90, 0xbd, 0xe4, 0x9e, 0xf0, 0x1e, 0xb3, 0x1a, 0xd4, 0xee, 0xec, 0x06, 0x7c, 0xf9,
	0x59, 0x41, 0xed, 0xca, 0x62, 0xf0, 0x0e, 0xce, 0x76, 0xf4, 0xb0, 0xb1, 0xc3, 0x4b, 0x9a, 0x69,
	0xfb, 0xcf, 0x4f, 0xcc, 0x08, 0x1d, 0x9c, 0xfe, 0x85, 0xa1, 0xb2, 0x83, 0xe6, 0xb3, 0xc6, 0x0e,
	0x5b, 0x99, 0xd1, 0xed, 0xd1, 0x63, 0x9d, 0x48, 0x3e, 0x48, 0x9e, 0xeb, 0x72, 0xb0, 0xab, 0xaf,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x83, 0xa8, 0x11, 0x69, 0xc0, 0x01, 0x00, 0x00,
}
