// Code generated by protoc-gen-go. DO NOT EDIT.
// source: conman.proto

package server

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ContainerState int32

const (
	ContainerState_CREATED ContainerState = 0
	ContainerState_RUNNING ContainerState = 1
	ContainerState_EXITED  ContainerState = 2
	ContainerState_UNKNOWN ContainerState = 3
)

var ContainerState_name = map[int32]string{
	0: "CREATED",
	1: "RUNNING",
	2: "EXITED",
	3: "UNKNOWN",
}
var ContainerState_value = map[string]int32{
	"CREATED": 0,
	"RUNNING": 1,
	"EXITED":  2,
	"UNKNOWN": 3,
}

func (x ContainerState) String() string {
	return proto.EnumName(ContainerState_name, int32(x))
}
func (ContainerState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_conman_e7bdb580f56683a6, []int{0}
}

type VersionRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VersionRequest) Reset()         { *m = VersionRequest{} }
func (m *VersionRequest) String() string { return proto.CompactTextString(m) }
func (*VersionRequest) ProtoMessage()    {}
func (*VersionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_conman_e7bdb580f56683a6, []int{0}
}
func (m *VersionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VersionRequest.Unmarshal(m, b)
}
func (m *VersionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VersionRequest.Marshal(b, m, deterministic)
}
func (dst *VersionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VersionRequest.Merge(dst, src)
}
func (m *VersionRequest) XXX_Size() int {
	return xxx_messageInfo_VersionRequest.Size(m)
}
func (m *VersionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VersionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VersionRequest proto.InternalMessageInfo

type VersionResponse struct {
	Version              string   `protobuf:"bytes,1,opt,name=version" json:"version,omitempty"`
	RuntimeName          string   `protobuf:"bytes,2,opt,name=runtime_name,json=runtimeName" json:"runtime_name,omitempty"`
	RuntimeVersion       string   `protobuf:"bytes,3,opt,name=runtime_version,json=runtimeVersion" json:"runtime_version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VersionResponse) Reset()         { *m = VersionResponse{} }
func (m *VersionResponse) String() string { return proto.CompactTextString(m) }
func (*VersionResponse) ProtoMessage()    {}
func (*VersionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_conman_e7bdb580f56683a6, []int{1}
}
func (m *VersionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VersionResponse.Unmarshal(m, b)
}
func (m *VersionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VersionResponse.Marshal(b, m, deterministic)
}
func (dst *VersionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VersionResponse.Merge(dst, src)
}
func (m *VersionResponse) XXX_Size() int {
	return xxx_messageInfo_VersionResponse.Size(m)
}
func (m *VersionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VersionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VersionResponse proto.InternalMessageInfo

func (m *VersionResponse) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *VersionResponse) GetRuntimeName() string {
	if m != nil {
		return m.RuntimeName
	}
	return ""
}

func (m *VersionResponse) GetRuntimeVersion() string {
	if m != nil {
		return m.RuntimeVersion
	}
	return ""
}

type CreateContainerRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	RootfsPath           string   `protobuf:"bytes,2,opt,name=rootfs_path,json=rootfsPath" json:"rootfs_path,omitempty"`
	RootfsReadonly       bool     `protobuf:"varint,3,opt,name=rootfs_readonly,json=rootfsReadonly" json:"rootfs_readonly,omitempty"`
	Command              string   `protobuf:"bytes,4,opt,name=command" json:"command,omitempty"`
	Args                 []string `protobuf:"bytes,5,rep,name=args" json:"args,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateContainerRequest) Reset()         { *m = CreateContainerRequest{} }
func (m *CreateContainerRequest) String() string { return proto.CompactTextString(m) }
func (*CreateContainerRequest) ProtoMessage()    {}
func (*CreateContainerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_conman_e7bdb580f56683a6, []int{2}
}
func (m *CreateContainerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateContainerRequest.Unmarshal(m, b)
}
func (m *CreateContainerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateContainerRequest.Marshal(b, m, deterministic)
}
func (dst *CreateContainerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateContainerRequest.Merge(dst, src)
}
func (m *CreateContainerRequest) XXX_Size() int {
	return xxx_messageInfo_CreateContainerRequest.Size(m)
}
func (m *CreateContainerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateContainerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateContainerRequest proto.InternalMessageInfo

func (m *CreateContainerRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateContainerRequest) GetRootfsPath() string {
	if m != nil {
		return m.RootfsPath
	}
	return ""
}

func (m *CreateContainerRequest) GetRootfsReadonly() bool {
	if m != nil {
		return m.RootfsReadonly
	}
	return false
}

func (m *CreateContainerRequest) GetCommand() string {
	if m != nil {
		return m.Command
	}
	return ""
}

func (m *CreateContainerRequest) GetArgs() []string {
	if m != nil {
		return m.Args
	}
	return nil
}

type CreateContainerResponse struct {
	ContainerId          string   `protobuf:"bytes,1,opt,name=container_id,json=containerId" json:"container_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateContainerResponse) Reset()         { *m = CreateContainerResponse{} }
func (m *CreateContainerResponse) String() string { return proto.CompactTextString(m) }
func (*CreateContainerResponse) ProtoMessage()    {}
func (*CreateContainerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_conman_e7bdb580f56683a6, []int{3}
}
func (m *CreateContainerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateContainerResponse.Unmarshal(m, b)
}
func (m *CreateContainerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateContainerResponse.Marshal(b, m, deterministic)
}
func (dst *CreateContainerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateContainerResponse.Merge(dst, src)
}
func (m *CreateContainerResponse) XXX_Size() int {
	return xxx_messageInfo_CreateContainerResponse.Size(m)
}
func (m *CreateContainerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateContainerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateContainerResponse proto.InternalMessageInfo

func (m *CreateContainerResponse) GetContainerId() string {
	if m != nil {
		return m.ContainerId
	}
	return ""
}

type StartContainerRequest struct {
	ContainerId          string   `protobuf:"bytes,1,opt,name=container_id,json=containerId" json:"container_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartContainerRequest) Reset()         { *m = StartContainerRequest{} }
func (m *StartContainerRequest) String() string { return proto.CompactTextString(m) }
func (*StartContainerRequest) ProtoMessage()    {}
func (*StartContainerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_conman_e7bdb580f56683a6, []int{4}
}
func (m *StartContainerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartContainerRequest.Unmarshal(m, b)
}
func (m *StartContainerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartContainerRequest.Marshal(b, m, deterministic)
}
func (dst *StartContainerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartContainerRequest.Merge(dst, src)
}
func (m *StartContainerRequest) XXX_Size() int {
	return xxx_messageInfo_StartContainerRequest.Size(m)
}
func (m *StartContainerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StartContainerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StartContainerRequest proto.InternalMessageInfo

func (m *StartContainerRequest) GetContainerId() string {
	if m != nil {
		return m.ContainerId
	}
	return ""
}

type StartContainerResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartContainerResponse) Reset()         { *m = StartContainerResponse{} }
func (m *StartContainerResponse) String() string { return proto.CompactTextString(m) }
func (*StartContainerResponse) ProtoMessage()    {}
func (*StartContainerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_conman_e7bdb580f56683a6, []int{5}
}
func (m *StartContainerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartContainerResponse.Unmarshal(m, b)
}
func (m *StartContainerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartContainerResponse.Marshal(b, m, deterministic)
}
func (dst *StartContainerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartContainerResponse.Merge(dst, src)
}
func (m *StartContainerResponse) XXX_Size() int {
	return xxx_messageInfo_StartContainerResponse.Size(m)
}
func (m *StartContainerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StartContainerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StartContainerResponse proto.InternalMessageInfo

type StopContainerRequest struct {
	ContainerId string `protobuf:"bytes,1,opt,name=container_id,json=containerId" json:"container_id,omitempty"`
	// Timeout in seconds before forcebly killing container (SIGKILL)
	Timeout              int64    `protobuf:"varint,2,opt,name=timeout" json:"timeout,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StopContainerRequest) Reset()         { *m = StopContainerRequest{} }
func (m *StopContainerRequest) String() string { return proto.CompactTextString(m) }
func (*StopContainerRequest) ProtoMessage()    {}
func (*StopContainerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_conman_e7bdb580f56683a6, []int{6}
}
func (m *StopContainerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StopContainerRequest.Unmarshal(m, b)
}
func (m *StopContainerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StopContainerRequest.Marshal(b, m, deterministic)
}
func (dst *StopContainerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StopContainerRequest.Merge(dst, src)
}
func (m *StopContainerRequest) XXX_Size() int {
	return xxx_messageInfo_StopContainerRequest.Size(m)
}
func (m *StopContainerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StopContainerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StopContainerRequest proto.InternalMessageInfo

func (m *StopContainerRequest) GetContainerId() string {
	if m != nil {
		return m.ContainerId
	}
	return ""
}

func (m *StopContainerRequest) GetTimeout() int64 {
	if m != nil {
		return m.Timeout
	}
	return 0
}

type StopContainerResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StopContainerResponse) Reset()         { *m = StopContainerResponse{} }
func (m *StopContainerResponse) String() string { return proto.CompactTextString(m) }
func (*StopContainerResponse) ProtoMessage()    {}
func (*StopContainerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_conman_e7bdb580f56683a6, []int{7}
}
func (m *StopContainerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StopContainerResponse.Unmarshal(m, b)
}
func (m *StopContainerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StopContainerResponse.Marshal(b, m, deterministic)
}
func (dst *StopContainerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StopContainerResponse.Merge(dst, src)
}
func (m *StopContainerResponse) XXX_Size() int {
	return xxx_messageInfo_StopContainerResponse.Size(m)
}
func (m *StopContainerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StopContainerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StopContainerResponse proto.InternalMessageInfo

type RemoveContainerRequest struct {
	ContainerId          string   `protobuf:"bytes,1,opt,name=container_id,json=containerId" json:"container_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveContainerRequest) Reset()         { *m = RemoveContainerRequest{} }
func (m *RemoveContainerRequest) String() string { return proto.CompactTextString(m) }
func (*RemoveContainerRequest) ProtoMessage()    {}
func (*RemoveContainerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_conman_e7bdb580f56683a6, []int{8}
}
func (m *RemoveContainerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveContainerRequest.Unmarshal(m, b)
}
func (m *RemoveContainerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveContainerRequest.Marshal(b, m, deterministic)
}
func (dst *RemoveContainerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveContainerRequest.Merge(dst, src)
}
func (m *RemoveContainerRequest) XXX_Size() int {
	return xxx_messageInfo_RemoveContainerRequest.Size(m)
}
func (m *RemoveContainerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveContainerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveContainerRequest proto.InternalMessageInfo

func (m *RemoveContainerRequest) GetContainerId() string {
	if m != nil {
		return m.ContainerId
	}
	return ""
}

type RemoveContainerResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveContainerResponse) Reset()         { *m = RemoveContainerResponse{} }
func (m *RemoveContainerResponse) String() string { return proto.CompactTextString(m) }
func (*RemoveContainerResponse) ProtoMessage()    {}
func (*RemoveContainerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_conman_e7bdb580f56683a6, []int{9}
}
func (m *RemoveContainerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveContainerResponse.Unmarshal(m, b)
}
func (m *RemoveContainerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveContainerResponse.Marshal(b, m, deterministic)
}
func (dst *RemoveContainerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveContainerResponse.Merge(dst, src)
}
func (m *RemoveContainerResponse) XXX_Size() int {
	return xxx_messageInfo_RemoveContainerResponse.Size(m)
}
func (m *RemoveContainerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveContainerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveContainerResponse proto.InternalMessageInfo

type ListContainersRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListContainersRequest) Reset()         { *m = ListContainersRequest{} }
func (m *ListContainersRequest) String() string { return proto.CompactTextString(m) }
func (*ListContainersRequest) ProtoMessage()    {}
func (*ListContainersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_conman_e7bdb580f56683a6, []int{10}
}
func (m *ListContainersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListContainersRequest.Unmarshal(m, b)
}
func (m *ListContainersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListContainersRequest.Marshal(b, m, deterministic)
}
func (dst *ListContainersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListContainersRequest.Merge(dst, src)
}
func (m *ListContainersRequest) XXX_Size() int {
	return xxx_messageInfo_ListContainersRequest.Size(m)
}
func (m *ListContainersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListContainersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListContainersRequest proto.InternalMessageInfo

type ListContainersResponse struct {
	Containers           []*Container `protobuf:"bytes,1,rep,name=containers" json:"containers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ListContainersResponse) Reset()         { *m = ListContainersResponse{} }
func (m *ListContainersResponse) String() string { return proto.CompactTextString(m) }
func (*ListContainersResponse) ProtoMessage()    {}
func (*ListContainersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_conman_e7bdb580f56683a6, []int{11}
}
func (m *ListContainersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListContainersResponse.Unmarshal(m, b)
}
func (m *ListContainersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListContainersResponse.Marshal(b, m, deterministic)
}
func (dst *ListContainersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListContainersResponse.Merge(dst, src)
}
func (m *ListContainersResponse) XXX_Size() int {
	return xxx_messageInfo_ListContainersResponse.Size(m)
}
func (m *ListContainersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListContainersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListContainersResponse proto.InternalMessageInfo

func (m *ListContainersResponse) GetContainers() []*Container {
	if m != nil {
		return m.Containers
	}
	return nil
}

type ContainerStatusRequest struct {
	ContainerId          string   `protobuf:"bytes,1,opt,name=container_id,json=containerId" json:"container_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ContainerStatusRequest) Reset()         { *m = ContainerStatusRequest{} }
func (m *ContainerStatusRequest) String() string { return proto.CompactTextString(m) }
func (*ContainerStatusRequest) ProtoMessage()    {}
func (*ContainerStatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_conman_e7bdb580f56683a6, []int{12}
}
func (m *ContainerStatusRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContainerStatusRequest.Unmarshal(m, b)
}
func (m *ContainerStatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContainerStatusRequest.Marshal(b, m, deterministic)
}
func (dst *ContainerStatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContainerStatusRequest.Merge(dst, src)
}
func (m *ContainerStatusRequest) XXX_Size() int {
	return xxx_messageInfo_ContainerStatusRequest.Size(m)
}
func (m *ContainerStatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ContainerStatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ContainerStatusRequest proto.InternalMessageInfo

func (m *ContainerStatusRequest) GetContainerId() string {
	if m != nil {
		return m.ContainerId
	}
	return ""
}

type ContainerStatusResponse struct {
	Status               *ContainerStatus `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ContainerStatusResponse) Reset()         { *m = ContainerStatusResponse{} }
func (m *ContainerStatusResponse) String() string { return proto.CompactTextString(m) }
func (*ContainerStatusResponse) ProtoMessage()    {}
func (*ContainerStatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_conman_e7bdb580f56683a6, []int{13}
}
func (m *ContainerStatusResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContainerStatusResponse.Unmarshal(m, b)
}
func (m *ContainerStatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContainerStatusResponse.Marshal(b, m, deterministic)
}
func (dst *ContainerStatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContainerStatusResponse.Merge(dst, src)
}
func (m *ContainerStatusResponse) XXX_Size() int {
	return xxx_messageInfo_ContainerStatusResponse.Size(m)
}
func (m *ContainerStatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ContainerStatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ContainerStatusResponse proto.InternalMessageInfo

func (m *ContainerStatusResponse) GetStatus() *ContainerStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

type Container struct {
	Id   string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	// Unix time in nanoseconds
	CreatedAt            int64          `protobuf:"varint,3,opt,name=created_at,json=createdAt" json:"created_at,omitempty"`
	State                ContainerState `protobuf:"varint,4,opt,name=state,enum=ContainerState" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Container) Reset()         { *m = Container{} }
func (m *Container) String() string { return proto.CompactTextString(m) }
func (*Container) ProtoMessage()    {}
func (*Container) Descriptor() ([]byte, []int) {
	return fileDescriptor_conman_e7bdb580f56683a6, []int{14}
}
func (m *Container) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Container.Unmarshal(m, b)
}
func (m *Container) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Container.Marshal(b, m, deterministic)
}
func (dst *Container) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Container.Merge(dst, src)
}
func (m *Container) XXX_Size() int {
	return xxx_messageInfo_Container.Size(m)
}
func (m *Container) XXX_DiscardUnknown() {
	xxx_messageInfo_Container.DiscardUnknown(m)
}

var xxx_messageInfo_Container proto.InternalMessageInfo

func (m *Container) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Container) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Container) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *Container) GetState() ContainerState {
	if m != nil {
		return m.State
	}
	return ContainerState_CREATED
}

type ContainerStatus struct {
	ContainerId   string         `protobuf:"bytes,1,opt,name=container_id,json=containerId" json:"container_id,omitempty"`
	ContainerName string         `protobuf:"bytes,2,opt,name=container_name,json=containerName" json:"container_name,omitempty"`
	State         ContainerState `protobuf:"varint,3,opt,name=state,enum=ContainerState" json:"state,omitempty"`
	// Unix time in nanoseconds
	CreatedAt int64 `protobuf:"varint,4,opt,name=created_at,json=createdAt" json:"created_at,omitempty"`
	// Unix time in nanoseconds
	StartedAt int64 `protobuf:"varint,5,opt,name=started_at,json=startedAt" json:"started_at,omitempty"`
	// Unix time in nanoseconds
	FinishedAt int64 `protobuf:"varint,6,opt,name=finished_at,json=finishedAt" json:"finished_at,omitempty"`
	// Exit code, relevant only if finished_at != 0.
	ExitCode int32 `protobuf:"varint,7,opt,name=exit_code,json=exitCode" json:"exit_code,omitempty"`
	// Human-readable note on the current container state.
	Message string `protobuf:"bytes,8,opt,name=message" json:"message,omitempty"`
	// Relative to conman's log dir path to container's log file.
	LogPath              string   `protobuf:"bytes,9,opt,name=log_path,json=logPath" json:"log_path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ContainerStatus) Reset()         { *m = ContainerStatus{} }
func (m *ContainerStatus) String() string { return proto.CompactTextString(m) }
func (*ContainerStatus) ProtoMessage()    {}
func (*ContainerStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_conman_e7bdb580f56683a6, []int{15}
}
func (m *ContainerStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContainerStatus.Unmarshal(m, b)
}
func (m *ContainerStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContainerStatus.Marshal(b, m, deterministic)
}
func (dst *ContainerStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContainerStatus.Merge(dst, src)
}
func (m *ContainerStatus) XXX_Size() int {
	return xxx_messageInfo_ContainerStatus.Size(m)
}
func (m *ContainerStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_ContainerStatus.DiscardUnknown(m)
}

var xxx_messageInfo_ContainerStatus proto.InternalMessageInfo

func (m *ContainerStatus) GetContainerId() string {
	if m != nil {
		return m.ContainerId
	}
	return ""
}

func (m *ContainerStatus) GetContainerName() string {
	if m != nil {
		return m.ContainerName
	}
	return ""
}

func (m *ContainerStatus) GetState() ContainerState {
	if m != nil {
		return m.State
	}
	return ContainerState_CREATED
}

func (m *ContainerStatus) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *ContainerStatus) GetStartedAt() int64 {
	if m != nil {
		return m.StartedAt
	}
	return 0
}

func (m *ContainerStatus) GetFinishedAt() int64 {
	if m != nil {
		return m.FinishedAt
	}
	return 0
}

func (m *ContainerStatus) GetExitCode() int32 {
	if m != nil {
		return m.ExitCode
	}
	return 0
}

func (m *ContainerStatus) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *ContainerStatus) GetLogPath() string {
	if m != nil {
		return m.LogPath
	}
	return ""
}

type AttachRequest struct {
	ContainerId          string   `protobuf:"bytes,1,opt,name=container_id,json=containerId" json:"container_id,omitempty"`
	Tty                  bool     `protobuf:"varint,2,opt,name=tty" json:"tty,omitempty"`
	Stdin                bool     `protobuf:"varint,3,opt,name=stdin" json:"stdin,omitempty"`
	Stdout               bool     `protobuf:"varint,4,opt,name=stdout" json:"stdout,omitempty"`
	Stderr               bool     `protobuf:"varint,5,opt,name=stderr" json:"stderr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AttachRequest) Reset()         { *m = AttachRequest{} }
func (m *AttachRequest) String() string { return proto.CompactTextString(m) }
func (*AttachRequest) ProtoMessage()    {}
func (*AttachRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_conman_e7bdb580f56683a6, []int{16}
}
func (m *AttachRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AttachRequest.Unmarshal(m, b)
}
func (m *AttachRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AttachRequest.Marshal(b, m, deterministic)
}
func (dst *AttachRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AttachRequest.Merge(dst, src)
}
func (m *AttachRequest) XXX_Size() int {
	return xxx_messageInfo_AttachRequest.Size(m)
}
func (m *AttachRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AttachRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AttachRequest proto.InternalMessageInfo

func (m *AttachRequest) GetContainerId() string {
	if m != nil {
		return m.ContainerId
	}
	return ""
}

func (m *AttachRequest) GetTty() bool {
	if m != nil {
		return m.Tty
	}
	return false
}

func (m *AttachRequest) GetStdin() bool {
	if m != nil {
		return m.Stdin
	}
	return false
}

func (m *AttachRequest) GetStdout() bool {
	if m != nil {
		return m.Stdout
	}
	return false
}

func (m *AttachRequest) GetStderr() bool {
	if m != nil {
		return m.Stderr
	}
	return false
}

type AttachResponse struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AttachResponse) Reset()         { *m = AttachResponse{} }
func (m *AttachResponse) String() string { return proto.CompactTextString(m) }
func (*AttachResponse) ProtoMessage()    {}
func (*AttachResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_conman_e7bdb580f56683a6, []int{17}
}
func (m *AttachResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AttachResponse.Unmarshal(m, b)
}
func (m *AttachResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AttachResponse.Marshal(b, m, deterministic)
}
func (dst *AttachResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AttachResponse.Merge(dst, src)
}
func (m *AttachResponse) XXX_Size() int {
	return xxx_messageInfo_AttachResponse.Size(m)
}
func (m *AttachResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AttachResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AttachResponse proto.InternalMessageInfo

func (m *AttachResponse) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func init() {
	proto.RegisterType((*VersionRequest)(nil), "VersionRequest")
	proto.RegisterType((*VersionResponse)(nil), "VersionResponse")
	proto.RegisterType((*CreateContainerRequest)(nil), "CreateContainerRequest")
	proto.RegisterType((*CreateContainerResponse)(nil), "CreateContainerResponse")
	proto.RegisterType((*StartContainerRequest)(nil), "StartContainerRequest")
	proto.RegisterType((*StartContainerResponse)(nil), "StartContainerResponse")
	proto.RegisterType((*StopContainerRequest)(nil), "StopContainerRequest")
	proto.RegisterType((*StopContainerResponse)(nil), "StopContainerResponse")
	proto.RegisterType((*RemoveContainerRequest)(nil), "RemoveContainerRequest")
	proto.RegisterType((*RemoveContainerResponse)(nil), "RemoveContainerResponse")
	proto.RegisterType((*ListContainersRequest)(nil), "ListContainersRequest")
	proto.RegisterType((*ListContainersResponse)(nil), "ListContainersResponse")
	proto.RegisterType((*ContainerStatusRequest)(nil), "ContainerStatusRequest")
	proto.RegisterType((*ContainerStatusResponse)(nil), "ContainerStatusResponse")
	proto.RegisterType((*Container)(nil), "Container")
	proto.RegisterType((*ContainerStatus)(nil), "ContainerStatus")
	proto.RegisterType((*AttachRequest)(nil), "AttachRequest")
	proto.RegisterType((*AttachResponse)(nil), "AttachResponse")
	proto.RegisterEnum("ContainerState", ContainerState_name, ContainerState_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Conman service

type ConmanClient interface {
	Version(ctx context.Context, in *VersionRequest, opts ...grpc.CallOption) (*VersionResponse, error)
	CreateContainer(ctx context.Context, in *CreateContainerRequest, opts ...grpc.CallOption) (*CreateContainerResponse, error)
	StartContainer(ctx context.Context, in *StartContainerRequest, opts ...grpc.CallOption) (*StartContainerResponse, error)
	StopContainer(ctx context.Context, in *StopContainerRequest, opts ...grpc.CallOption) (*StopContainerResponse, error)
	RemoveContainer(ctx context.Context, in *RemoveContainerRequest, opts ...grpc.CallOption) (*RemoveContainerResponse, error)
	ListContainers(ctx context.Context, in *ListContainersRequest, opts ...grpc.CallOption) (*ListContainersResponse, error)
	ContainerStatus(ctx context.Context, in *ContainerStatusRequest, opts ...grpc.CallOption) (*ContainerStatusResponse, error)
	Attach(ctx context.Context, in *AttachRequest, opts ...grpc.CallOption) (*AttachResponse, error)
}

type conmanClient struct {
	cc *grpc.ClientConn
}

func NewConmanClient(cc *grpc.ClientConn) ConmanClient {
	return &conmanClient{cc}
}

func (c *conmanClient) Version(ctx context.Context, in *VersionRequest, opts ...grpc.CallOption) (*VersionResponse, error) {
	out := new(VersionResponse)
	err := grpc.Invoke(ctx, "/Conman/Version", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *conmanClient) CreateContainer(ctx context.Context, in *CreateContainerRequest, opts ...grpc.CallOption) (*CreateContainerResponse, error) {
	out := new(CreateContainerResponse)
	err := grpc.Invoke(ctx, "/Conman/CreateContainer", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *conmanClient) StartContainer(ctx context.Context, in *StartContainerRequest, opts ...grpc.CallOption) (*StartContainerResponse, error) {
	out := new(StartContainerResponse)
	err := grpc.Invoke(ctx, "/Conman/StartContainer", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *conmanClient) StopContainer(ctx context.Context, in *StopContainerRequest, opts ...grpc.CallOption) (*StopContainerResponse, error) {
	out := new(StopContainerResponse)
	err := grpc.Invoke(ctx, "/Conman/StopContainer", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *conmanClient) RemoveContainer(ctx context.Context, in *RemoveContainerRequest, opts ...grpc.CallOption) (*RemoveContainerResponse, error) {
	out := new(RemoveContainerResponse)
	err := grpc.Invoke(ctx, "/Conman/RemoveContainer", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *conmanClient) ListContainers(ctx context.Context, in *ListContainersRequest, opts ...grpc.CallOption) (*ListContainersResponse, error) {
	out := new(ListContainersResponse)
	err := grpc.Invoke(ctx, "/Conman/ListContainers", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *conmanClient) ContainerStatus(ctx context.Context, in *ContainerStatusRequest, opts ...grpc.CallOption) (*ContainerStatusResponse, error) {
	out := new(ContainerStatusResponse)
	err := grpc.Invoke(ctx, "/Conman/ContainerStatus", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *conmanClient) Attach(ctx context.Context, in *AttachRequest, opts ...grpc.CallOption) (*AttachResponse, error) {
	out := new(AttachResponse)
	err := grpc.Invoke(ctx, "/Conman/Attach", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Conman service

type ConmanServer interface {
	Version(context.Context, *VersionRequest) (*VersionResponse, error)
	CreateContainer(context.Context, *CreateContainerRequest) (*CreateContainerResponse, error)
	StartContainer(context.Context, *StartContainerRequest) (*StartContainerResponse, error)
	StopContainer(context.Context, *StopContainerRequest) (*StopContainerResponse, error)
	RemoveContainer(context.Context, *RemoveContainerRequest) (*RemoveContainerResponse, error)
	ListContainers(context.Context, *ListContainersRequest) (*ListContainersResponse, error)
	ContainerStatus(context.Context, *ContainerStatusRequest) (*ContainerStatusResponse, error)
	Attach(context.Context, *AttachRequest) (*AttachResponse, error)
}

func RegisterConmanServer(s *grpc.Server, srv ConmanServer) {
	s.RegisterService(&_Conman_serviceDesc, srv)
}

func _Conman_Version_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConmanServer).Version(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Conman/Version",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConmanServer).Version(ctx, req.(*VersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Conman_CreateContainer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateContainerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConmanServer).CreateContainer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Conman/CreateContainer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConmanServer).CreateContainer(ctx, req.(*CreateContainerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Conman_StartContainer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartContainerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConmanServer).StartContainer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Conman/StartContainer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConmanServer).StartContainer(ctx, req.(*StartContainerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Conman_StopContainer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopContainerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConmanServer).StopContainer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Conman/StopContainer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConmanServer).StopContainer(ctx, req.(*StopContainerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Conman_RemoveContainer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveContainerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConmanServer).RemoveContainer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Conman/RemoveContainer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConmanServer).RemoveContainer(ctx, req.(*RemoveContainerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Conman_ListContainers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListContainersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConmanServer).ListContainers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Conman/ListContainers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConmanServer).ListContainers(ctx, req.(*ListContainersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Conman_ContainerStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContainerStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConmanServer).ContainerStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Conman/ContainerStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConmanServer).ContainerStatus(ctx, req.(*ContainerStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Conman_Attach_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AttachRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConmanServer).Attach(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Conman/Attach",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConmanServer).Attach(ctx, req.(*AttachRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Conman_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Conman",
	HandlerType: (*ConmanServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Version",
			Handler:    _Conman_Version_Handler,
		},
		{
			MethodName: "CreateContainer",
			Handler:    _Conman_CreateContainer_Handler,
		},
		{
			MethodName: "StartContainer",
			Handler:    _Conman_StartContainer_Handler,
		},
		{
			MethodName: "StopContainer",
			Handler:    _Conman_StopContainer_Handler,
		},
		{
			MethodName: "RemoveContainer",
			Handler:    _Conman_RemoveContainer_Handler,
		},
		{
			MethodName: "ListContainers",
			Handler:    _Conman_ListContainers_Handler,
		},
		{
			MethodName: "ContainerStatus",
			Handler:    _Conman_ContainerStatus_Handler,
		},
		{
			MethodName: "Attach",
			Handler:    _Conman_Attach_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "conman.proto",
}

func init() { proto.RegisterFile("conman.proto", fileDescriptor_conman_e7bdb580f56683a6) }

var fileDescriptor_conman_e7bdb580f56683a6 = []byte{
	// 804 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x56, 0xdd, 0x8e, 0xdb, 0x44,
	0x18, 0x4d, 0xe2, 0x6c, 0x7e, 0xbe, 0x74, 0x1d, 0x6b, 0xd4, 0xb5, 0xdd, 0xa0, 0x8a, 0x74, 0xa4,
	0x8a, 0xa8, 0x48, 0x73, 0x11, 0xee, 0x80, 0x0b, 0x82, 0xbb, 0xa0, 0x15, 0x28, 0x20, 0x87, 0x02,
	0xe2, 0x26, 0x32, 0xf1, 0x34, 0xb1, 0x14, 0x7b, 0xc2, 0xcc, 0x64, 0xa1, 0x8f, 0x00, 0xcf, 0xc1,
	0x1b, 0xf0, 0x82, 0x68, 0x7e, 0xe2, 0x5d, 0x3b, 0xde, 0xaa, 0xed, 0xdd, 0xcc, 0x39, 0x33, 0xdf,
	0x5f, 0xce, 0x1c, 0x07, 0x1e, 0x6d, 0x58, 0x91, 0x27, 0x05, 0x39, 0x70, 0x26, 0x19, 0xf6, 0xc0,
	0xfd, 0x99, 0x72, 0x91, 0xb1, 0x22, 0xa6, 0x7f, 0x1c, 0xa9, 0x90, 0xf8, 0x4f, 0x18, 0x97, 0x88,
	0x38, 0xb0, 0x42, 0x50, 0x14, 0x42, 0xff, 0xd6, 0x40, 0x61, 0x7b, 0xda, 0x9e, 0x0d, 0xe3, 0xd3,
	0x16, 0x3d, 0x83, 0x47, 0xfc, 0x58, 0xc8, 0x2c, 0xa7, 0xeb, 0x22, 0xc9, 0x69, 0xd8, 0xd1, 0xf4,
	0xc8, 0x62, 0xcb, 0x24, 0xa7, 0xe8, 0x13, 0x18, 0x9f, 0x8e, 0x9c, 0x82, 0x38, 0xfa, 0x94, 0x6b,
	0x61, 0x9b, 0x0d, 0xff, 0xdb, 0x06, 0x3f, 0xe2, 0x34, 0x91, 0x34, 0x62, 0x85, 0x4c, 0xb2, 0x82,
	0x72, 0x5b, 0x13, 0x42, 0xd0, 0xd5, 0xe1, 0x4d, 0x76, 0xbd, 0x46, 0x1f, 0xc3, 0x88, 0x33, 0x26,
	0x5f, 0x8b, 0xf5, 0x21, 0x91, 0x3b, 0x9b, 0x19, 0x0c, 0xf4, 0x63, 0x22, 0x77, 0x3a, 0xb1, 0x39,
	0xc0, 0x69, 0x92, 0xb2, 0x62, 0xff, 0x46, 0x27, 0x1e, 0xc4, 0xae, 0x81, 0x63, 0x8b, 0xaa, 0xf6,
	0x36, 0x2c, 0xcf, 0x93, 0x22, 0x0d, 0xbb, 0xa6, 0x3d, 0xbb, 0x55, 0x79, 0x13, 0xbe, 0x15, 0xe1,
	0xc5, 0xd4, 0x51, 0x79, 0xd5, 0x1a, 0x7f, 0x09, 0xc1, 0x59, 0x95, 0x76, 0x4e, 0xcf, 0xf4, 0x70,
	0x0d, 0xb8, 0xce, 0x52, 0x5b, 0xee, 0xa8, 0xc4, 0x6e, 0x52, 0xfc, 0x39, 0x5c, 0xad, 0x64, 0xc2,
	0xe5, 0x59, 0x8b, 0xef, 0x70, 0x37, 0x04, 0xbf, 0x7e, 0xd7, 0x24, 0xc6, 0x2b, 0x78, 0xbc, 0x92,
	0xec, 0xf0, 0x01, 0x41, 0x55, 0xf3, 0xea, 0x47, 0x60, 0x47, 0xa9, 0x47, 0xe8, 0xc4, 0xa7, 0x2d,
	0x0e, 0x54, 0xa9, 0x95, 0xa0, 0x36, 0xdb, 0x17, 0xe0, 0xc7, 0x34, 0x67, 0xb7, 0xf4, 0x43, 0x9a,
	0x78, 0x02, 0xc1, 0xd9, 0x65, 0x1b, 0x37, 0x80, 0xab, 0xef, 0x33, 0x71, 0xd7, 0x9e, 0x38, 0x49,
	0xf2, 0x25, 0xf8, 0x75, 0xc2, 0x4e, 0xfc, 0x05, 0x40, 0x19, 0x5c, 0x84, 0xed, 0xa9, 0x33, 0x1b,
	0xcd, 0x81, 0xdc, 0x85, 0xbe, 0xc7, 0xaa, 0xb2, 0x4b, 0x62, 0x25, 0x13, 0x79, 0x14, 0xef, 0x51,
	0x76, 0x04, 0xc1, 0xd9, 0x65, 0x5b, 0xc3, 0x0c, 0x7a, 0x42, 0x23, 0xfa, 0xde, 0x68, 0xee, 0x91,
	0xfa, 0x49, 0xcb, 0xe3, 0x23, 0x0c, 0x4b, 0x0a, 0xb9, 0xd0, 0x29, 0x53, 0x75, 0xb2, 0xb4, 0xd4,
	0x78, 0xe7, 0x9e, 0xc6, 0x9f, 0x02, 0x6c, 0xb4, 0xd6, 0xd2, 0x75, 0x22, 0xb5, 0x7a, 0x9d, 0x78,
	0x68, 0x91, 0x85, 0x44, 0xcf, 0xe1, 0x42, 0x45, 0xa6, 0x5a, 0xb6, 0xee, 0x7c, 0x5c, 0x4d, 0x4c,
	0x63, 0xc3, 0xe2, 0xff, 0x3a, 0x30, 0xae, 0x95, 0xf4, 0x2e, 0xca, 0x78, 0x0e, 0xee, 0xdd, 0x91,
	0x7b, 0xa5, 0x5d, 0x96, 0xa8, 0x7e, 0xdf, 0x65, 0x11, 0xce, 0xdb, 0x8a, 0xa8, 0xb5, 0xd2, 0xad,
	0xb7, 0xf2, 0x14, 0x40, 0x28, 0x6d, 0x1b, 0xfa, 0xc2, 0xd0, 0x16, 0x59, 0x48, 0xf5, 0xd8, 0x5f,
	0x67, 0x45, 0x26, 0x76, 0x86, 0xef, 0x69, 0x1e, 0x4e, 0xd0, 0x42, 0xa2, 0x8f, 0x60, 0x48, 0xff,
	0xca, 0xe4, 0x7a, 0xc3, 0x52, 0x1a, 0xf6, 0xa7, 0xed, 0xd9, 0x45, 0x3c, 0x50, 0x40, 0xc4, 0x52,
	0xed, 0x5f, 0x39, 0x15, 0x22, 0xd9, 0xd2, 0x70, 0x60, 0x1e, 0xb8, 0xdd, 0xa2, 0x27, 0x30, 0xd8,
	0xb3, 0xad, 0x71, 0x90, 0xa1, 0xa1, 0xf6, 0x6c, 0xab, 0xec, 0x03, 0xff, 0xd3, 0x86, 0xcb, 0x85,
	0x94, 0xc9, 0x66, 0xf7, 0x1e, 0xaf, 0xc9, 0x03, 0x47, 0xca, 0x37, 0x7a, 0x50, 0x83, 0x58, 0x2d,
	0xd1, 0x63, 0x35, 0x9e, 0x34, 0x2b, 0xac, 0xf7, 0x98, 0x0d, 0xf2, 0x95, 0x66, 0x52, 0xf5, 0xe8,
	0xba, 0x1a, 0xb6, 0x3b, 0x8b, 0x53, 0xce, 0xf5, 0x08, 0x0c, 0x4e, 0x39, 0xc7, 0x18, 0xdc, 0x53,
	0x2d, 0x56, 0x75, 0x1e, 0x38, 0x47, 0xbe, 0xb7, 0x35, 0xa8, 0xe5, 0x8b, 0x08, 0xdc, 0xea, 0xe8,
	0xd1, 0x08, 0xfa, 0x51, 0x7c, 0xbd, 0xf8, 0xe9, 0xfa, 0xa5, 0xd7, 0x52, 0x9b, 0xf8, 0xd5, 0x72,
	0x79, 0xb3, 0xfc, 0xd6, 0x6b, 0x23, 0x80, 0xde, 0xf5, 0xaf, 0x37, 0x8a, 0xe8, 0x28, 0xe2, 0xd5,
	0xf2, 0xbb, 0xe5, 0x0f, 0xbf, 0x2c, 0x3d, 0x67, 0xfe, 0x77, 0x17, 0x7a, 0x91, 0xfe, 0x40, 0x20,
	0x02, 0x7d, 0x6b, 0xcd, 0x68, 0x4c, 0xaa, 0x1f, 0x89, 0x89, 0x47, 0x6a, 0xdf, 0x08, 0xdc, 0x42,
	0xdf, 0xc0, 0xb8, 0x66, 0x8c, 0x28, 0x20, 0xcd, 0x86, 0x3e, 0x09, 0xc9, 0x03, 0x1e, 0x8a, 0x5b,
	0x28, 0x02, 0xb7, 0x6a, 0x73, 0xc8, 0x27, 0x8d, 0x9e, 0x39, 0x09, 0xc8, 0x03, 0x7e, 0xd8, 0x42,
	0x5f, 0xc1, 0x65, 0xc5, 0xbc, 0xd0, 0x15, 0x69, 0x72, 0xc8, 0x89, 0x4f, 0x9a, 0x3d, 0x4e, 0xb7,
	0x53, 0x33, 0x2a, 0x14, 0x90, 0x66, 0xdf, 0x9b, 0x84, 0xe4, 0x21, 0x4f, 0xd3, 0xed, 0x54, 0xcd,
	0x0b, 0xf9, 0xa4, 0xd1, 0xe6, 0x26, 0x01, 0x69, 0x76, 0x39, 0x3b, 0xdb, 0xda, 0x0b, 0x0e, 0x48,
	0xb3, 0x9b, 0xa9, 0xd9, 0x36, 0x3b, 0x15, 0x6e, 0xa1, 0x4f, 0xa1, 0x67, 0x74, 0x84, 0x5c, 0x52,
	0x11, 0xf7, 0x64, 0x4c, 0xaa, 0x02, 0xc3, 0xad, 0xaf, 0x07, 0xbf, 0xf5, 0x04, 0xe5, 0xb7, 0x94,
	0xff, 0xde, 0xd3, 0x7f, 0x16, 0x3e, 0xfb, 0x3f, 0x00, 0x00, 0xff, 0xff, 0x6a, 0x33, 0x66, 0xea,
	0x3c, 0x08, 0x00, 0x00,
}
